import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TableProgressbar, { List } from "@/components/TableProgressbar";
import Avatar from "@/components/Avatar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const firstList: List[] = [
    {
      id: 1,
      name: "Figma",
      number: 100,
    },
    {
      id: 2,
      name: "Prototyping",
      number: 100,
    },
    {
      id: 3,
      name: "UX Wireframing",
      number: 100,
    },
  ];

  const secondList: List[] = [
    {
      id: 1,
      name: "Mentorship",
      number: 88,
    },
    {
      id: 2,
      name: "Collaboration",
      number: 100,
    },
    {
      id: 3,
      name: "Empathy",
      number: 82,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            borderRadius: "40px",
            width: "400px",
            backgroundColor: "# F9FAFB",
            padding: "32px",
          }}
        >
          <Avatar title="Theodore Taylor" description="Sr. Product Designer" />
          <TableProgressbar title="Top Hard Skills" list={firstList} />
          <TableProgressbar title="Top Soft Skills" list={secondList} />
        </div>
      </main>
    </>
  );
}
